### ISSUE TITLE
Create mockups for new documentation site

### ISSUE THREAD

**Issue by notoriousb1t** [just-animate/just-animate.github.io#3]
As discussed on the just-animate channel on animationatwork slack

**Comment by josephrexme** [comment]
Adding these here as approved from the chat. I'll create a new issue for the development of these mockups.

![just animate](https://user-images.githubusercontent.com/5395567/29368889-9b587150-8266-11e7-8caf-e70cc2a5e67f.jpg)

<hr />

![just animate - documentation](https://user-images.githubusercontent.com/5395567/29368915-b26097e2-8266-11e7-9004-eb9ad798a485.jpg)
