### ISSUE TITLE
On first load buttons stack (Chrome)

### ISSUE THREAD

**Issue by notoriousb1t** [just-animate/just-animate.github.io#6]
There appears to be an issue in Chrome where sometimes the dropdowns stack the first time it is loaded into a tab.

![capture](https://user-images.githubusercontent.com/736847/29670273-27f4d498-88b4-11e7-9b19-7933e5a11244.JPG)

**Comment by josephrexme** [comment]
I noticed this too. I'll try to find what's responsible for that
