### ISSUE TITLE
API Reference tables are not being rendered

### ISSUE THREAD

**Issue by notoriousb1t** [just-animate/just-animate.github.io#7]
Maybe this is a difference in the markdown renderer between jenkins and gitbooks:

https://just-animate.github.io/api/

We need to either display this differently or figure out a way to get the markdown generator to show tables here.

**Comment by josephrexme** [comment]
Oh that's something with the markdown engine being used I think. Default is `kramdown` but I had encountered some problems with it not rendering properly so I used `redcarpet` as shown here

https://github.com/just-animate/just-animate.github.io/blob/source/_config.yml#L9

I think now that it builds generated pages into master without relying on GitHub for it I should be able to use kramdown again or I could look for another markdown engine that works

**Comment by josephrexme** [comment]
Tested with kramdown and it handles tables fine but I remember the problem with it was how it handles code blocks with language type for syntax coloring

<img width="797" alt="screenshot 2017-08-30 12 55 10" src="https://user-images.githubusercontent.com/5395567/29887266-795f06be-8d82-11e7-8501-5e6fb9992bcd.png">

I'll have to look for a markdown engine that handles both fine

**Comment by notoriousb1t** [comment]
Cool.  Thank you for fixing this 😄 !
